// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxywFVAe1AnBIJbzLkLL3dE35aD5ekl04',
    appId: '1:614054881461:web:dfb2bdc0be50ed671cf6fc',
    messagingSenderId: '614054881461',
    projectId: 'movieapp-dfdcd',
    authDomain: 'movieapp-dfdcd.firebaseapp.com',
    storageBucket: 'movieapp-dfdcd.firebasestorage.app',
    measurementId: 'G-KMH61CHSE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEgQXRPEcHs3Oowj0p5nI1sD2coJBN5Yo',
    appId: '1:614054881461:android:e14fc2c945ad1b081cf6fc',
    messagingSenderId: '614054881461',
    projectId: 'movieapp-dfdcd',
    storageBucket: 'movieapp-dfdcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi-1UrtEM5DhpmRMs-WWALVnvuAphrix8',
    appId: '1:614054881461:ios:18b2a6ccf78d418a1cf6fc',
    messagingSenderId: '614054881461',
    projectId: 'movieapp-dfdcd',
    storageBucket: 'movieapp-dfdcd.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi-1UrtEM5DhpmRMs-WWALVnvuAphrix8',
    appId: '1:614054881461:ios:18b2a6ccf78d418a1cf6fc',
    messagingSenderId: '614054881461',
    projectId: 'movieapp-dfdcd',
    storageBucket: 'movieapp-dfdcd.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxywFVAe1AnBIJbzLkLL3dE35aD5ekl04',
    appId: '1:614054881461:web:d182d50c4d5846511cf6fc',
    messagingSenderId: '614054881461',
    projectId: 'movieapp-dfdcd',
    authDomain: 'movieapp-dfdcd.firebaseapp.com',
    storageBucket: 'movieapp-dfdcd.firebasestorage.app',
    measurementId: 'G-8SWH6F8KN6',
  );
}
